import { EntryType } from '../../domain/entry/entry.entity';
import type { CreateEntryProps } from '../../domain/entry/entry.entity';

type SeedEntry = Omit<CreateEntryProps, 'isOfficial' | 'isHomebrew' | 'createdBy' | 'isPublic'>;

// ─── D&D 5e Classes (Core) ────────────────────────────────────────────────────

export const D5E_CLASSES: SeedEntry[] = [
  {
    name: 'Barbarian',
    description:
      'A fierce warrior who taps into a well of power to fuel his incredible combat prowess. At 1st level, a barbarian can enter a controlled rage.',
    shortDescription: 'Fierce melee combatant with rage ability.',
    type: EntryType.CLASS,
    system: 'd5e',
    tags: ['class', 'barbarian', 'melee', 'martial'],
    attributes: [
      { key: 'hit_die', value: 'd12', label: 'Hit Die' },
      { key: 'primary_ability', value: 'STR', label: 'Habilidade Primária' },
      { key: 'saving_throw', value: 'STR, CON', label: 'Saving Throws' },
      { key: 'proficiency', value: 'Simple & Martial Weapons, Shields', label: 'Proficiência' },
      { key: 'spell_ability', value: 'None', label: 'Magia' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 46 },
  },
  {
    name: 'Bard',
    description:
      'An inspiring magician whose powers are fueled by performance and personality. The bard is a master of culture and learning.',
    shortDescription: 'Magic-based charisma caster with support abilities.',
    type: EntryType.CLASS,
    system: 'd5e',
    tags: ['class', 'bard', 'caster', 'support'],
    attributes: [
      { key: 'hit_die', value: 'd8', label: 'Hit Die' },
      { key: 'primary_ability', value: 'CHA', label: 'Habilidade Primária' },
      { key: 'saving_throw', value: 'DEX, CHA', label: 'Saving Throws' },
      { key: 'spell_ability', value: 'CHA', label: 'Magia' },
      { key: 'spells_known', value: 'Knows cantrips & spells', label: 'Conhecimento' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 51 },
  },
  {
    name: 'Cleric',
    description:
      'A priestly champion who wields divine magic in service of a higher power. The cleric is a master of healing and support magic.',
    shortDescription: 'Divine spellcaster with healing and support.',
    type: EntryType.CLASS,
    system: 'd5e',
    tags: ['class', 'cleric', 'divine', 'support', 'healing'],
    attributes: [
      { key: 'hit_die', value: 'd8', label: 'Hit Die' },
      { key: 'primary_ability', value: 'WIS', label: 'Habilidade Primária' },
      { key: 'saving_throw', value: 'WIS, CHA', label: 'Saving Throws' },
      { key: 'spell_ability', value: 'WIS', label: 'Magia' },
      { key: 'channel_divinity', value: 'Twice per rest at 1st level', label: 'Channel Divinity' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 58 },
  },
  {
    name: 'Druid',
    description:
      'A priest of the Old Faith, wielding the powers of nature. The druid is a master of animal handling and nature magic.',
    shortDescription: 'Nature spellcaster with wild shape ability.',
    type: EntryType.CLASS,
    system: 'd5e',
    tags: ['class', 'druid', 'nature', 'wildshape'],
    attributes: [
      { key: 'hit_die', value: 'd8', label: 'Hit Die' },
      { key: 'primary_ability', value: 'WIS', label: 'Habilidade Primária' },
      { key: 'saving_throw', value: 'INT, WIS', label: 'Saving Throws' },
      { key: 'spell_ability', value: 'WIS', label: 'Magia' },
      { key: 'wild_shape', value: 'Transform into animals', label: 'Wild Shape' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 66 },
  },
  {
    name: 'Fighter',
    description:
      'A master of martial combat. The fighter is a master of weapons and armor, excelling in close quarters combat.',
    shortDescription: 'Skilled martial combatant with multiple attacks.',
    type: EntryType.CLASS,
    system: 'd5e',
    tags: ['class', 'fighter', 'martial', 'melee'],
    attributes: [
      { key: 'hit_die', value: 'd10', label: 'Hit Die' },
      { key: 'primary_ability', value: 'STR or DEX', label: 'Habilidade Primária' },
      { key: 'saving_throw', value: 'STR, CON', label: 'Saving Throws' },
      { key: 'extra_attack', value: 'Starting at 5th level', label: 'Extra Attack' },
      { key: 'fighting_style', value: 'Archery, Defense, Dueling, Great Weapon, etc', label: 'Fighting Style' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 70 },
  },
  {
    name: 'Monk',
    description:
      'A master of martial arts. The monk harnesses the power of the body to achieve extraordinary feats of combat.',
    shortDescription: 'Martial artist with ki points and unarmed combat.',
    type: EntryType.CLASS,
    system: 'd5e',
    tags: ['class', 'monk', 'martial', 'unarmed'],
    attributes: [
      { key: 'hit_die', value: 'd8', label: 'Hit Die' },
      { key: 'primary_ability', value: 'DEX, WIS', label: 'Habilidade Primária' },
      { key: 'saving_throw', value: 'STR, DEX', label: 'Saving Throws' },
      { key: 'ki_points', value: 'Level equal to monastic level', label: 'Ki Points' },
      { key: 'unarmed_strike', value: '1d4 at 1st, scales with level', label: 'Unarmed Strike' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 76 },
  },
  {
    name: 'Paladin',
    description:
      'A holy warrior bound by a sacred oath. The paladin is a master of divine magic and melee combat.',
    shortDescription: 'Divine warrior with smite and healing.',
    type: EntryType.CLASS,
    system: 'd5e',
    tags: ['class', 'paladin', 'divine', 'martial'],
    attributes: [
      { key: 'hit_die', value: 'd10', label: 'Hit Die' },
      { key: 'primary_ability', value: 'STR, CHA', label: 'Habilidade Primária' },
      { key: 'saving_throw', value: 'WIS, CHA', label: 'Saving Throws' },
      { key: 'spell_ability', value: 'CHA', label: 'Magia' },
      { key: 'divine_smite', value: 'Add spell slot to damage roll', label: 'Divine Smite' },
      { key: 'lay_on_hands', value: 'Heal or cure poison', label: 'Lay on Hands' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 82 },
  },
  {
    name: 'Ranger',
    description:
      'A warrior who hunts the wilderness. The ranger is a master of ranged weapons and survival skills.',
    shortDescription: 'Martial tracker with ranged combat and spellcasting.',
    type: EntryType.CLASS,
    system: 'd5e',
    tags: ['class', 'ranger', 'ranged', 'survival'],
    attributes: [
      { key: 'hit_die', value: 'd10', label: 'Hit Die' },
      { key: 'primary_ability', value: 'DEX, WIS', label: 'Habilidade Primária' },
      { key: 'saving_throw', value: 'STR, DEX', label: 'Saving Throws' },
      { key: 'spell_ability', value: 'WIS', label: 'Magia' },
      { key: 'favored_enemy', value: 'Bonus vs specific enemy type', label: 'Favored Enemy' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 89 },
  },
  {
    name: 'Rogue',
    description:
      'A scoundrel who uses stealth and trickery to prevail in any situation. The rogue is a master of skills.',
    shortDescription: 'Stealthy skilled combatant with sneak attack.',
    type: EntryType.CLASS,
    system: 'd5e',
    tags: ['class', 'rogue', 'stealth', 'skills'],
    attributes: [
      { key: 'hit_die', value: 'd8', label: 'Hit Die' },
      { key: 'primary_ability', value: 'DEX', label: 'Habilidade Primária' },
      { key: 'saving_throw', value: 'DEX, INT', label: 'Saving Throws' },
      { key: 'expertise', value: '2 skills at 1st level', label: 'Expertise' },
      { key: 'sneak_attack', value: '1d6 extra damage', label: 'Sneak Attack' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 94 },
  },
  {
    name: 'Sorcerer',
    description:
      'A spellcaster who has innate magical power flowing through his veins. The sorcerer is a master of raw arcane magic.',
    shortDescription: 'Charisma-based spontaneous spellcaster.',
    type: EntryType.CLASS,
    system: 'd5e',
    tags: ['class', 'sorcerer', 'arcane', 'spellcaster'],
    attributes: [
      { key: 'hit_die', value: 'd6', label: 'Hit Die' },
      { key: 'primary_ability', value: 'CHA', label: 'Habilidade Primária' },
      { key: 'saving_throw', value: 'CON, CHA', label: 'Saving Throws' },
      { key: 'spell_ability', value: 'CHA', label: 'Magia' },
      { key: 'sorcery_points', value: 'Cast spells without preparing', label: 'Sorcery Points' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 99 },
  },
  {
    name: 'Warlock',
    description:
      'A spellcaster who has made a pact with an otherworldly power. The warlock wields invocation-based magic.',
    shortDescription: 'Charisma-based pact magic with invocations.',
    type: EntryType.CLASS,
    system: 'd5e',
    tags: ['class', 'warlock', 'pact', 'spellcaster'],
    attributes: [
      { key: 'hit_die', value: 'd8', label: 'Hit Die' },
      { key: 'primary_ability', value: 'CHA', label: 'Habilidade Primária' },
      { key: 'saving_throw', value: 'WIS, CHA', label: 'Saving Throws' },
      { key: 'spell_ability', value: 'CHA', label: 'Magia' },
      { key: 'pact_slots', value: 'All slots are highest level', label: 'Pact Slots' },
      { key: 'eldritch_invocation', value: 'Customize spellcasting', label: 'Eldritch Invocation' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 105 },
  },
  {
    name: 'Wizard',
    description:
      'A scholarly spellcaster who has devoted himself to the study of the arcane arts. The wizard is a master of prepared spellcasting.',
    shortDescription: 'Intelligence-based prepared spellcaster.',
    type: EntryType.CLASS,
    system: 'd5e',
    tags: ['class', 'wizard', 'arcane', 'scholar'],
    attributes: [
      { key: 'hit_die', value: 'd6', label: 'Hit Die' },
      { key: 'primary_ability', value: 'INT', label: 'Habilidade Primária' },
      { key: 'saving_throw', value: 'INT, WIS', label: 'Saving Throws' },
      { key: 'spell_ability', value: 'INT', label: 'Magia' },
      { key: 'spellbook', value: 'Prepare spells from spellbook', label: 'Spellbook' },
      { key: 'arcane_tradition', value: 'Specialist at 2nd level', label: 'Arcane Tradition' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 112 },
  },
];

// ─── D&D 5e Races ────────────────────────────────────────────────────────────

export const D5E_RACES: SeedEntry[] = [
  {
    name: 'Dwarf',
    description:
      'Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal. They stand about 4-5 feet tall and weigh about 150 pounds.',
    shortDescription: 'Skilled warriors and crafters, 4-5 feet tall.',
    type: EntryType.RACE,
    system: 'd5e',
    tags: ['race', 'dwarf', 'martial', 'mountain'],
    attributes: [
      { key: 'size', value: 'Medium', label: 'Tamanho' },
      { key: 'speed', value: '25 ft', label: 'Velocidade' },
      { key: 'ability_bonus', value: '+2 CON', label: 'Bônus de Atributo' },
      { key: 'lifespan', value: '350 years', label: 'Lifespan' },
      { key: 'darkvision', value: '60 feet', label: 'Visão no Escuro' },
      { key: 'languages', value: 'Common, Dwarvish', label: 'Idiomas' },
      { key: 'resistance', value: 'Poison resistance', label: 'Resistência' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 168 },
  },
  {
    name: 'Elf',
    description:
      'Elves are a magical people of otherworldly grace, living in the world but not entirely part of it. They live for several centuries, giving them a broad perspective.',
    shortDescription: 'Graceful magical beings, 5-6 feet tall.',
    type: EntryType.RACE,
    system: 'd5e',
    tags: ['race', 'elf', 'magical', 'graceful'],
    attributes: [
      { key: 'size', value: 'Medium', label: 'Tamanho' },
      { key: 'speed', value: '30 ft', label: 'Velocidade' },
      { key: 'ability_bonus', value: '+2 DEX', label: 'Bônus de Atributo' },
      { key: 'lifespan', value: '750 years', label: 'Lifespan' },
      { key: 'darkvision', value: '60 feet', label: 'Visão no Escuro' },
      { key: 'languages', value: 'Common, Elvish', label: 'Idiomas' },
      { key: 'keensenses', value: 'Advantage on Wisdom (Perception) checks', label: 'Keen Senses' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 173 },
  },
  {
    name: 'Halfling',
    description:
      'The diminutive halflings have earned a reputation as exceptional thieves and adventurers. They stand about 3 feet tall and weigh about 35 pounds.',
    shortDescription: 'Small brave adventurers, 3 feet tall.',
    type: EntryType.RACE,
    system: 'd5e',
    tags: ['race', 'halfling', 'small', 'lucky'],
    attributes: [
      { key: 'size', value: 'Small', label: 'Tamanho' },
      { key: 'speed', value: '25 ft', label: 'Velocidade' },
      { key: 'ability_bonus', value: '+2 DEX', label: 'Bônus de Atributo' },
      { key: 'lifespan', value: '150 years', label: 'Lifespan' },
      { key: 'lucky', value: 'Reroll 1s', label: 'Lucky' },
      { key: 'languages', value: 'Common, Halfling', label: 'Idiomas' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 177 },
  },
  {
    name: 'Human',
    description:
      'Humans are the most adaptable and ambitious people of the world. They have widely varying tastes, morals, and customs in the many different lands where they have settled.',
    shortDescription: 'Versatile and ambitious, 5-6 feet tall.',
    type: EntryType.RACE,
    system: 'd5e',
    tags: ['race', 'human', 'versatile', 'ambitious'],
    attributes: [
      { key: 'size', value: 'Medium', label: 'Tamanho' },
      { key: 'speed', value: '30 ft', label: 'Velocidade' },
      { key: 'ability_bonus', value: '+1 all abilities', label: 'Bônus de Atributo' },
      { key: 'lifespan', value: '80 years', label: 'Lifespan' },
      { key: 'feat', value: 'Gain one feat at 1st level', label: 'Feat' },
      { key: 'languages', value: 'Common + 1 other', label: 'Idiomas' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 181 },
  },
  {
    name: 'Dragonborn',
    description:
      'Dragonborn are imposing draconic humanoids. They stand more than 6 feet tall, with scaly skin that harkens back to their draconic ancestry.',
    shortDescription: 'Draconic humanoids, 6-7 feet tall.',
    type: EntryType.RACE,
    system: 'd5e',
    tags: ['race', 'dragonborn', 'draconic', 'strong'],
    attributes: [
      { key: 'size', value: 'Medium', label: 'Tamanho' },
      { key: 'speed', value: '30 ft', label: 'Velocidade' },
      { key: 'ability_bonus', value: '+2 STR, +1 CHA', label: 'Bônus de Atributo' },
      { key: 'lifespan', value: '80 years', label: 'Lifespan' },
      { key: 'breath_weapon', value: 'Chosen at character creation', label: 'Breath Weapon' },
      { key: 'languages', value: 'Common, Draconic', label: 'Idiomas' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 183 },
  },
  {
    name: 'Gnome',
    description:
      'A gnome\'s energy and enthusiasm for living shines through every inch of his or her tiny body. Gnomes average slightly over 3 feet tall and weigh 40-45 pounds.',
    shortDescription: 'Inventive small humanoids, 3+ feet tall.',
    type: EntryType.RACE,
    system: 'd5e',
    tags: ['race', 'gnome', 'inventive', 'small'],
    attributes: [
      { key: 'size', value: 'Small', label: 'Tamanho' },
      { key: 'speed', value: '25 ft', label: 'Velocidade' },
      { key: 'ability_bonus', value: '+2 INT', label: 'Bônus de Atributo' },
      { key: 'lifespan', value: '500 years', label: 'Lifespan' },
      { key: 'darkvision', value: '60 feet', label: 'Visão no Escuro' },
      { key: 'languages', value: 'Common, Gnomish', label: 'Idiomas' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 186 },
  },
  {
    name: 'Half-Elf',
    description:
      'Half-elves inherit a blend of physical features, both human and elven. They have the agility of their elven heritage and the ambition of their human side.',
    shortDescription: 'Blend of human and elf, 5-6 feet tall.',
    type: EntryType.RACE,
    system: 'd5e',
    tags: ['race', 'half-elf', 'flexible', 'charismatic'],
    attributes: [
      { key: 'size', value: 'Medium', label: 'Tamanho' },
      { key: 'speed', value: '30 ft', label: 'Velocidade' },
      { key: 'ability_bonus', value: '+2 CHA, +1 two abilities', label: 'Bônus de Atributo' },
      { key: 'lifespan', value: '180 years', label: 'Lifespan' },
      { key: 'darkvision', value: '60 feet', label: 'Visão no Escuro' },
      { key: 'languages', value: 'Common, Elvish, 1 more', label: 'Idiomas' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 190 },
  },
  {
    name: 'Half-Orc',
    description:
      'Half-orcs inherit a blotchy coloration, sloping foreheads, jutting jaws, prominent teeth, and towering builds from their orcish heritage. They average nearly 7 feet tall.',
    shortDescription: 'Strong orcish humanoid, 6-7 feet tall.',
    type: EntryType.RACE,
    system: 'd5e',
    tags: ['race', 'half-orc', 'strong', 'intimidating'],
    attributes: [
      { key: 'size', value: 'Medium', label: 'Tamanho' },
      { key: 'speed', value: '30 ft', label: 'Velocidade' },
      { key: 'ability_bonus', value: '+2 STR, +1 CON', label: 'Bônus de Atributo' },
      { key: 'lifespan', value: '75 years', label: 'Lifespan' },
      { key: 'darkvision', value: '60 feet', label: 'Visão no Escuro' },
      { key: 'languages', value: 'Common, Orc', label: 'Idiomas' },
      { key: 'relentless_endurance', value: 'Ignore damage once per rest', label: 'Relentless Endurance' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 193 },
  },
  {
    name: 'Tiefling',
    description:
      'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling. And yet these humans clad in exotic appearances.',
    shortDescription: 'Infernal humanoid with tail, 5-6 feet tall.',
    type: EntryType.RACE,
    system: 'd5e',
    tags: ['race', 'tiefling', 'infernal', 'magical'],
    attributes: [
      { key: 'size', value: 'Medium', label: 'Tamanho' },
      { key: 'speed', value: '30 ft', label: 'Velocidade' },
      { key: 'ability_bonus', value: '+2 CHA, +1 INT', label: 'Bônus de Atributo' },
      { key: 'lifespan', value: '100 years', label: 'Lifespan' },
      { key: 'darkvision', value: '60 feet', label: 'Visão no Escuro' },
      { key: 'languages', value: 'Common, Infernal', label: 'Idiomas' },
      { key: 'infernal_legacy', value: 'Spellcasting innate', label: 'Infernal Legacy' },
    ],
    relations: [],
    source: { book: 'Player\'s Handbook', page: 196 },
  },
];

export const D5E_DATA_ALL = [...D5E_CLASSES, ...D5E_RACES];
