import { EntryType } from '../../domain/entry/entry.entity';
import type { CreateEntryProps } from '../../domain/entry/entry.entity';

type SeedEntry = Omit<CreateEntryProps, 'isOfficial' | 'isHomebrew' | 'createdBy' | 'isPublic'>;

// ─── Monstros Tormenta20 (Expandidos) ──────────────────────────────────────────

export const T20_MONSTROS_EXPANDIDOS: SeedEntry[] = [
  {
    name: 'Kobold Guerreiro',
    description:
      'Humanoides reptilianos pequenos. Os Kobolds são mestres em armadilhas e combate em grupo. Normalmente vivem em masmorras profundas. Esse espécime é um guerreiro veterano armado com lança e escudo.',
    shortDescription: 'Humanoide reptiliano pequeno, guerreiro em grupo.',
    type: EntryType.MONSTER,
    system: 'tormenta20',
    tags: ['monstro', 'kobold', 'guerreiro', 'nd-1/4'],
    attributes: [
      { key: 'cr', value: '1/4', label: 'ND' },
      { key: 'size', value: 'Pequeno', label: 'Tamanho' },
      { key: 'hp', value: '5 (2d6 - 2)', label: 'PV' },
      { key: 'ac', value: '15 (escudo)', label: 'CA' },
      { key: 'speed', value: '6m', label: 'Velocidade' },
      { key: 'str', value: '7 (-2)', label: 'FOR' },
      { key: 'dex', value: '15 (+2)', label: 'DES' },
      { key: 'con', value: '9 (-1)', label: 'CON' },
      { key: 'int', value: '8 (-1)', label: 'INT' },
      { key: 'wis', value: '7 (-2)', label: 'SAB' },
      { key: 'cha', value: '8 (-1)', label: 'CAR' },
      { key: 'skills', value: 'Furtividade +4', label: 'Perícias' },
      { key: 'senses', value: 'Visão no Escuro 18m, Percepção Passiva 8', label: 'Sentidos' },
      { key: 'languages', value: 'Dracônico', label: 'Idiomas' },
      { key: 'threat', value: 'Médio em número', label: 'Ameaça' },
    ],
    relations: [],
    source: { book: 'Tormenta20 Livro Básico', page: 290 },
  },
  {
    name: 'Orc Saqueador',
    description:
      'Humanoides brutais e fortes. Os Orcs são predadores naturais que vivem em clãs tribais nas terras selvagens. Esse espécime é um saqueador que viaja em pequenos grupos pilhando aldeias.',
    shortDescription: 'Humanoide brutal e forte, saqueador tribal.',
    type: EntryType.MONSTER,
    system: 'tormenta20',
    tags: ['monstro', 'orc', 'saqueador', 'nd-1/2'],
    attributes: [
      { key: 'cr', value: '1/2', label: 'ND' },
      { key: 'size', value: 'Grande', label: 'Tamanho' },
      { key: 'hp', value: '15 (2d10 + 4)', label: 'PV' },
      { key: 'ac', value: '12 (armadura de couro)', label: 'CA' },
      { key: 'speed', value: '9m', label: 'Velocidade' },
      { key: 'str', value: '16 (+3)', label: 'FOR' },
      { key: 'dex', value: '12 (+1)', label: 'DES' },
      { key: 'con', value: '15 (+2)', label: 'CON' },
      { key: 'int', value: '8 (-1)', label: 'INT' },
      { key: 'wis', value: '11 (0)', label: 'SAB' },
      { key: 'cha', value: '10 (0)', label: 'CAR' },
      { key: 'skills', value: 'Intimidação +2', label: 'Perícias' },
      { key: 'senses', value: 'Visão no Escuro 18m, Percepção Passiva 10', label: 'Sentidos' },
      { key: 'languages', value: 'Orc', label: 'Idiomas' },
      { key: 'actions', value: 'Golpe (Machado): +5 ataque, 1d12+3 dano', label: 'Ações' },
    ],
    relations: [],
    source: { book: 'Tormenta20 Livro Básico', page: 291 },
  },
  {
    name: 'Mago Necromante',
    description:
      'Um mago especializando em magia da morte. Capaz de invocar esqueletos e criar Zonas de Frio extremo. Seus olhos brilham com poder necromântico.',
    shortDescription: 'Mago especializado em magia negra e necromancia.',
    type: EntryType.MONSTER,
    system: 'tormenta20',
    tags: ['monstro', 'mago', 'necromancia', 'nd-3'],
    attributes: [
      { key: 'cr', value: '3', label: 'ND' },
      { key: 'size', value: 'Médio', label: 'Tamanho' },
      { key: 'hp', value: '27 (5d8 + 5)', label: 'PV' },
      { key: 'ac', value: '12 (manto)', label: 'CA' },
      { key: 'speed', value: '6m', label: 'Velocidade' },
      { key: 'str', value: '9 (-1)', label: 'FOR' },
      { key: 'dex', value: '12 (+1)', label: 'DES' },
      { key: 'con', value: '12 (+1)', label: 'CON' },
      { key: 'int', value: '16 (+3)', label: 'INT' },
      { key: 'wis', value: '13 (+1)', label: 'SAB' },
      { key: 'cha', value: '10 (0)', label: 'CAR' },
      { key: 'save', value: 'INT +5, SAB +3', label: 'Salvação' },
      { key: 'skills', value: 'Arcanismo +5, Percepção +3', label: 'Perícias' },
      { key: 'spells', value: 'Bola de Fogo, Morte Repentina, Invocar Espírito', label: 'Magias' },
      { key: 'threat', value: 'Alto - evitar confronto direto', label: 'Ameaça' },
    ],
    relations: [],
    source: { book: 'Tormenta20 Livro Básico', page: 292 },
  },
  {
    name: 'Sereia Guerreira',
    description:
      'Uma criatura aquática humanoide com rabo de peixe. Normalmente hostil com intrusos em seu território. Essa Sereia é especialmente agressiva, armada com tridente encarreiado.',
    shortDescription: 'Criatura aquática humanoide, agressiva.',
    type: EntryType.MONSTER,
    system: 'tormenta20',
    tags: ['monstro', 'sereia', 'aquático', 'nd-1'],
    attributes: [
      { key: 'cr', value: '1', label: 'ND' },
      { key: 'size', value: 'Médio', label: 'Tamanho' },
      { key: 'hp', value: '22 (3d8 + 9)', label: 'PV' },
      { key: 'ac', value: '13', label: 'CA' },
      { key: 'speed', value: '0m (nado 9m)', label: 'Velocidade' },
      { key: 'str', value: '14 (+2)', label: 'FOR' },
      { key: 'dex', value: '14 (+2)', label: 'DES' },
      { key: 'con', value: '16 (+3)', label: 'CON' },
      { key: 'int', value: '12 (+1)', label: 'INT' },
      { key: 'wis', value: '13 (+1)', label: 'SAB' },
      { key: 'cha', value: '14 (+2)', label: 'CAR' },
      { key: 'skills', value: 'Percepção +3, Perícia Aquática +4', label: 'Perícias' },
      { key: 'environment', value: 'Água (respiração', label: 'Ambiente' },
      { key: 'weakness', value: 'Vulnerável em terra', label: 'Fraqueza' },
    ],
    relations: [],
    source: { book: 'Tormenta20 Livro Básico', page: 293 },
  },
  {
    name: 'Golem de Pedra',
    description:
      'Uma construção mágica de pedra maciça. O Golem é praticamente indestrutível por meios convencionais e segue cegamente seus comandos de invocação. Imune a magia.',
    shortDescription: 'Construção mágica pétreo, quase indestrutível.',
    type: EntryType.MONSTER,
    system: 'tormenta20',
    tags: ['monstro', 'golem', 'construto', 'nd-5'],
    attributes: [
      { key: 'cr', value: '5', label: 'ND' },
      { key: 'size', value: 'Grande', label: 'Tamanho' },
      { key: 'hp', value: '52 (7d10 + 14)', label: 'PV' },
      { key: 'ac', value: '17 (resistência natural)', label: 'CA' },
      { key: 'speed', value: '6m', label: 'Velocidade' },
      { key: 'str', value: '20 (+5)', label: 'FOR' },
      { key: 'dex', value: '5 (-3)', label: 'DES' },
      { key: 'con', value: '18 (+4)', label: 'CON' },
      { key: 'int', value: '3 (-4)', label: 'INT' },
      { key: 'wis', value: '11 (0)', label: 'SAB' },
      { key: 'cha', value: '1 (-5)', label: 'CAR' },
      { key: 'immunity', value: 'Magia (absorve), Psique', label: 'Imunidade' },
      { key: 'weakness', value: 'Destruição (6 golpes críticos necessários)', label: 'Fraqueza' },
      { key: 'threat', value: 'Extremo - requer magia especializada', label: 'Ameaça' },
    ],
    relations: [],
    source: { book: 'Tormenta20 Livro Básico', page: 294 },
  },
  {
    name: 'Espectro Antigo',
    description:
      'Um fantasma de poderoso mago morto há séculos. Capaz de invocar magia e infligir amaldiçoamento. Aterroriza castelos e ruínas arcanas.',
    shortDescription: 'Fantasma de mago morto, pode amaldiçoar.',
    type: EntryType.MONSTER,
    system: 'tormenta20',
    tags: ['monstro', 'espectro', 'magia', 'nd-4', 'sobrenatural'],
    attributes: [
      { key: 'cr', value: '4', label: 'ND' },
      { key: 'size', value: 'Médio', label: 'Tamanho' },
      { key: 'hp', value: '40 (9d8)', label: 'PV' },
      { key: 'ac', value: '13', label: 'CA' },
      { key: 'speed', value: '0m (voo 9m invisível)', label: 'Velocidade' },
      { key: 'immunity', value: 'Magia, Frio, Raio, Psíquico', label: 'Imunidade' },
      { key: 'spells', value: 'Maldição, Enregelar, Toque Fantasmagórico', label: 'Habilidades' },
      { key: 'turn_resistance', value: 'Vantagem contra banimento', label: 'Resistência' },
      { key: 'weakness', value: 'Arma mágica de ouro consagrado', label: 'Fraqueza' },
      { key: 'threat', value: 'Alto - requer coragem e magia sagrada', label: 'Ameaça' },
    ],
    relations: [],
    source: { book: 'Tormenta20 Livro Básico', page: 295 },
  },
  {
    name: 'Hidra Aquática',
    description:
      'Uma criatura anfíbia com sete cabeças regeneratórias. Se uma cabeça for destruída, dois novos membros crescem. Habita lagoas profundas e rios selvagens.',
    shortDescription: 'Criatura anfíbia com sete cabeças regeneratórias.',
    type: EntryType.MONSTER,
    system: 'tormenta20',
    tags: ['monstro', 'hidra', 'aquático', 'nd-8', 'boss'],
    attributes: [
      { key: 'cr', value: '8', label: 'ND' },
      { key: 'size', value: 'Gigante', label: 'Tamanho' },
      { key: 'hp', value: '114 (12d12 + 36)', label: 'PV' },
      { key: 'ac', value: '15', label: 'CA' },
      { key: 'speed', value: '6m (nado 12m)', label: 'Velocidade' },
      { key: 'str', value: '19 (+4)', label: 'FOR' },
      { key: 'con', value: '17 (+3)', label: 'CON' },
      { key: 'regeneration', value: '5 PV/rodada por cabeça intacta', label: 'Regeneração' },
      { key: 'heads', value: '7 ataques por rodada (um por cabeça)', label: 'Múltiplos ataques' },
      { key: 'immunity', value: 'Envenenamento', label: 'Imunidade' },
      { key: 'threat', value: 'Extremo - requer grupo experiente', label: 'Ameaça' },
    ],
    relations: [],
    source: { book: 'Tormenta20 Livro Básico', page: 296 },
  },
  {
    name: 'Cavaleiro Negro',
    description:
      'Uma criatura humanoide envolvida em sombra, armada com espada maldita. Serve a poderes antigos e deixa morte onde passa. Praticamente indestrutível.',
    shortDescription: 'Cavaleiro envolvido em sombra, espada maldita.',
    type: EntryType.MONSTER,
    system: 'tormenta20',
    tags: ['monstro', 'cavaleiro', 'mal', 'nd-6', 'boss'],
    attributes: [
      { key: 'cr', value: '6', label: 'ND' },
      { key: 'size', value: 'Médio', label: 'Tamanho' },
      { key: 'hp', value: '78 (12d8 + 24)', label: 'PV' },
      { key: 'ac', value: '18 (armadura +2)', label: 'CA' },
      { key: 'speed', value: '6m', label: 'Velocidade' },
      { key: 'str', value: '18 (+4)', label: 'FOR' },
      { key: 'con', value: '16 (+3)', label: 'CON' },
      { key: 'resistance', value: 'Dano necrótico, Psíquico', label: 'Resistência' },
      { key: 'immunity', value: 'Frio', label: 'Imunidade' },
      { key: 'weakness', value: 'Luz solar, magia sagrada', label: 'Fraqueza' },
      { key: 'aura', value: 'Aura de Frio 9m: 1d6 dano frio/rodada', label: 'Aura' },
      { key: 'threat', value: 'Extremo - requer grupo de heróis', label: 'Ameaça' },
    ],
    relations: [],
    source: { book: 'Tormenta20 Livro Básico', page: 297 },
  },
  {
    name: 'Dragão Jovem Vermelho (ND 7)',
    description:
      'Um Dragão Vermelho em idade juvenil, ainda não totalmente desenvolvido mas extremamente perigoso. Respira fogo e possui tesouro substancial. Inteligência cruel e ambição desmedida.',
    shortDescription: 'Dragão jovem, respira fogo, extremamente inteligente.',
    type: EntryType.MONSTER,
    system: 'tormenta20',
    tags: ['monstro', 'dragão', 'vermelho', 'nd-7', 'boss', 'maior'],
    attributes: [
      { key: 'cr', value: '7', label: 'ND' },
      { key: 'size', value: 'Grande', label: 'Tamanho' },
      { key: 'hp', value: '110 (13d10 + 39)', label: 'PV' },
      { key: 'ac', value: '18', label: 'CA' },
      { key: 'speed', value: '9m (voo 18m)', label: 'Velocidade' },
      { key: 'str', value: '19 (+4)', label: 'FOR' },
      { key: 'con', value: '17 (+3)', label: 'CON' },
      { key: 'int', value: '16 (+3)', label: 'INT' },
      { key: 'senses', value: 'Visão Verdadeira 36m', label: 'Sentidos' },
      { key: 'immunity', value: 'Fogo', label: 'Imunidade' },
      { key: 'breath', value: 'Cone de fogo 9m: 10d6 dano (Reflexos metade)', label: 'Sopro' },
      { key: 'threat', value: 'Mortal - requer grande grupo ou estratégia', label: 'Ameaça' },
    ],
    relations: [],
    source: { book: 'Tormenta20 Livro Básico', page: 298 },
  },
  {
    name: 'Demônio Maior',
    description:
      'Uma entidade infernal de forma quasi-humanoide coberta em chamas. Pode invocar demonitos menores e lançar magia de alto círculo. Praticamente indestrutível sem armas sagradas.',
    shortDescription: 'Entidade infernal coberta em chamas, extremamente poderosa.',
    type: EntryType.MONSTER,
    system: 'tormenta20',
    tags: ['monstro', 'demônio', 'inferno', 'nd-10', 'boss', 'final'],
    attributes: [
      { key: 'cr', value: '10', label: 'ND' },
      { key: 'size', value: 'Grande', label: 'Tamanho' },
      { key: 'hp', value: '150 (12d12 + 72)', label: 'PV' },
      { key: 'ac', value: '17', label: 'CA' },
      { key: 'speed', value: '6m (voo 12m)', label: 'Velocidade' },
      { key: 'immunity', value: 'Fogo, Frio, Poção, Maldição', label: 'Imunidade' },
      { key: 'resistance', value: 'Magia (50%), Necrótico', label: 'Resistência' },
      { key: 'spells', value: 'Bola de Fogo, Toque Mortal, Escuridão Profunda', label: 'Magias' },
      { key: 'special', value: 'Invoca 1d4+2 demonitos menores', label: 'Habilidade Especial' },
      { key: 'threat', value: 'Mortal - morte certa sem preparação', label: 'Ameaça' },
    ],
    relations: [],
    source: { book: 'Tormenta20 Livro Básico', page: 299 },
  },
];

export const T20_MONSTROS_TOTAL = T20_MONSTROS_EXPANDIDOS;
